"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { CheckCircle2, Clock3, RefreshCw, Search, Trash2, XCircle } from "lucide-react";

type Waste = { id:number; number:string; trxDate:string; wasteQty:number; unitCost:number; totalCost:number; note:string|null; barang:{code:string;name:string;unit:string;stock:number}|null; user?:{fullname:string|null;username:string}|null };
const fmt=(v:number)=>new Intl.NumberFormat("id-ID",{maximumFractionDigits:2}).format(Number(v||0));
const money=(v:number)=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(Number(v||0));
const date=(v:string)=>new Intl.DateTimeFormat("id-ID",{day:"2-digit",month:"short",year:"numeric",hour:"2-digit",minute:"2-digit"}).format(new Date(v));

export default function WasteApprovalPusatPage(){
 const [data,setData]=useState<Waste[]>([]); const [search,setSearch]=useState(""); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState<number|null>(null); const [error,setError]=useState("");
 const load=useCallback(async()=>{try{setLoading(true);setError("");const r=await fetch("/api/waste?month=all&status=PENDING",{cache:"no-store"});const j=await r.json();if(!r.ok||!j.success)throw new Error(j.message||"Gagal mengambil approval Waste Pusat.");setData(Array.isArray(j.data)?j.data:[]);}catch(e){setError(e instanceof Error?e.message:"Gagal mengambil data.");}finally{setLoading(false);}},[]);
 useEffect(()=>{load()},[load]);
 const filtered=useMemo(()=>{const q=search.trim().toLowerCase();if(!q)return data;return data.filter(x=>[x.number,x.barang?.code,x.barang?.name,x.note,x.user?.fullname].filter(Boolean).some(v=>String(v).toLowerCase().includes(q)))},[data,search]);
 async function action(id:number,kind:"approve"|"reject"){const row=data.find(x=>x.id===id);if(!row)return;if(kind==="approve"&&!window.confirm(`Approve ${row.number}?\n\nStock pusat akan berkurang ${fmt(row.wasteQty)} ${row.barang?.unit||""}.`))return;let reason="";if(kind==="reject"){const r=window.prompt(`Alasan reject ${row.number}:`);if(r===null)return;if(!r.trim())return alert("Alasan reject wajib diisi.");reason=r.trim();}try{setBusy(id);const r=await fetch(`/api/waste/${id}/${kind}`,{method:"PUT",headers:{"Content-Type":"application/json"},body:kind==="reject"?JSON.stringify({reason}):undefined});const j=await r.json();if(!r.ok||!j.success)throw new Error(j.message||"Gagal memproses Waste.");setData(cur=>cur.filter(x=>x.id!==id));}catch(e){alert(e instanceof Error?e.message:"Gagal memproses Waste.")}finally{setBusy(null)}}
 return <div className="min-h-screen bg-[#F5F9F6] p-5 lg:p-8"><div className="mx-auto max-w-[1500px] space-y-6">
  <section className="rounded-[28px] border border-white bg-white p-6 shadow-[0_10px_40px_rgba(15,23,42,0.05)] sm:p-8"><div className="flex flex-col gap-5 lg:flex-row lg:items-center lg:justify-between"><div><div className="mb-3 flex items-center gap-2"><span className="h-2.5 w-2.5 rounded-full bg-amber-400"/><span className="text-xs font-bold uppercase tracking-[0.2em] text-amber-600">MGB ERP • APPROVAL</span></div><h1 className="flex items-center gap-3 text-2xl font-bold text-[#29483A] sm:text-3xl"><span className="flex h-11 w-11 items-center justify-center rounded-2xl bg-amber-50 text-amber-600"><Clock3/></span> Approval Waste Pusat</h1><p className="mt-2 text-sm text-[#71827A]">Review transaksi Waste sebelum pengurangan stock pusat.</p></div><button onClick={load} className="rounded-xl border border-slate-200 bg-white p-3 text-slate-500 hover:bg-emerald-50 hover:text-emerald-600"><RefreshCw size={18}/></button></div></section>
  <section className="rounded-2xl border border-[#DCE8E2] bg-white shadow-sm"><div className="flex flex-col gap-3 border-b border-slate-100 p-4 md:flex-row md:items-center md:justify-between"><div><p className="text-sm font-bold text-slate-800">Menunggu Approval</p><p className="mt-1 text-xs text-slate-400">{filtered.length} transaksi pending</p></div><div className="relative"><Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Cari waste / barang..." className="w-64 rounded-xl border border-slate-200 py-2.5 pl-9 pr-3 text-xs outline-none focus:border-[#497F70]"/></div></div>
  {error&&<div className="m-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</div>}
  <div className="overflow-x-auto"><table className="min-w-[1000px] w-full text-sm"><thead className="bg-slate-50/80"><tr>{["Waste","Tanggal","Barang","Qty","Nilai","Dibuat Oleh","Catatan","Aksi"].map(x=><th key={x} className="px-5 py-3 text-left text-[10px] font-bold uppercase tracking-wide text-slate-500">{x}</th>)}</tr></thead><tbody>{loading?<tr><td colSpan={8} className="py-20 text-center text-sm text-slate-400"><RefreshCw className="mx-auto mb-3 animate-spin text-emerald-600"/>Memuat...</td></tr>:filtered.length?filtered.map(x=><tr key={x.id} className="border-t border-slate-100 hover:bg-slate-50/60"><td className="px-5 py-4 font-bold text-[#497F70]">{x.number}</td><td className="px-5 py-4 text-xs text-slate-500">{date(x.trxDate)}</td><td className="px-5 py-4"><div className="font-semibold text-slate-700">{x.barang?.name}</div><div className="text-[11px] text-slate-400">{x.barang?.code} • Stock {fmt(x.barang?.stock||0)} {x.barang?.unit}</div></td><td className="px-5 py-4 font-semibold">{fmt(x.wasteQty)} {x.barang?.unit}</td><td className="px-5 py-4 font-semibold text-red-600">{money(x.totalCost)}</td><td className="px-5 py-4 text-xs text-slate-500">{x.user?.fullname||x.user?.username||"-"}</td><td className="max-w-[240px] px-5 py-4 text-xs text-slate-500">{x.note||"-"}</td><td className="px-5 py-4"><div className="flex gap-2"><button disabled={busy===x.id} onClick={()=>action(x.id,"approve")} className="inline-flex items-center gap-1 rounded-lg bg-[#497F70] px-3 py-2 text-xs font-semibold text-white disabled:opacity-50"><CheckCircle2 size={14}/>Approve</button><button disabled={busy===x.id} onClick={()=>action(x.id,"reject")} className="inline-flex items-center gap-1 rounded-lg bg-red-50 px-3 py-2 text-xs font-semibold text-red-600 disabled:opacity-50"><XCircle size={14}/>Reject</button></div></td></tr>):<tr><td colSpan={8} className="py-20 text-center"><div className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-emerald-50 text-emerald-600"><CheckCircle2/></div><p className="mt-3 text-sm font-semibold text-slate-700">Tidak ada Waste yang menunggu approval</p></td></tr>}</tbody></table></div></section>
 </div></div>
}
